# This file was generated by GoReleaser. DO NOT EDIT.
cask "apetrader" do
  name "apetrader"
  desc "Terminal-based AI trading assistant for SPY/SPX options."
  homepage "https://apetrade.com"
  version "0.1.12"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "apetrader"

  on_macos do
    on_intel do
      url "https://github.com/bearhedge/apetrade-releases/releases/download/v#{version}/apetrader-mac-x86_64.tar.gz"
      sha256 "dcd03c24f300ceb271bf235b1b5eaa73f76c18626caaadd6a1997f4fdf5a8088"
    end
    on_arm do
      url "https://github.com/bearhedge/apetrade-releases/releases/download/v#{version}/apetrader-mac-arm64.tar.gz"
      sha256 "43bdd635d171a06397a2531625e14cae07194712b263b72ca8d4bff2365a2353"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bearhedge/apetrade-releases/releases/download/v#{version}/apetrader-linux-x86_64.tar.gz"
      sha256 "9f129d6ba0dcbc53e8ce9abc459dec8eb852c974ea9e2b74cc8b29c8d6795198"
    end
    on_arm do
      url "https://github.com/bearhedge/apetrade-releases/releases/download/v#{version}/apetrader-linux-arm64.tar.gz"
      sha256 "c7abb2b925adde6ac612bd5091e659ab522c36e8a8184b2443ec3717c7a1cf6a"
    end
  end

  caveats do
    "Verify the active version with: apetrader --version"
    "If it differs from this installed version, run: type -a apetrader"
    "A previous curl installation in ~/.local/bin may precede Homebrew on PATH."
    "Run Homebrew's copy directly with: $(brew --prefix)/bin/apetrader"
    "Keep one installation method to avoid conflicting updates."
  end

  # No zap stanza required
end
