# This file was generated by GoReleaser. DO NOT EDIT.
cask "apetrader" do
  name "apetrader"
  desc "Terminal-based AI trading assistant for SPY/SPX options."
  homepage "https://apetrade.com"
  version "0.1.40"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "apetrader"

  on_macos do
    on_intel do
      url "https://github.com/bearhedge/apetrade-releases/releases/download/v#{version}/apetrader-mac-x86_64.tar.gz"
      sha256 "65f1a1cb9190309ed305cdcbb9ee551ee7c1d1dda42c51a3fa3c85bd127ac3f2"
    end
    on_arm do
      url "https://github.com/bearhedge/apetrade-releases/releases/download/v#{version}/apetrader-mac-arm64.tar.gz"
      sha256 "a3730440b4d370740547d72ea6cd0ec16d5d12104585280c088870647b0cf8d1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bearhedge/apetrade-releases/releases/download/v#{version}/apetrader-linux-x86_64.tar.gz"
      sha256 "311ec28e79df0101a7dcc947ca0c681d6a52a43cb65221fce5b0232ada4da63a"
    end
    on_arm do
      url "https://github.com/bearhedge/apetrade-releases/releases/download/v#{version}/apetrader-linux-arm64.tar.gz"
      sha256 "d29d3003c536459e4ad8393a18284490e54e09062fca0616cb6b24afa64c3ecc"
    end
  end

  caveats do
    "Verify the active version with: apetrader --version"
    "If it differs from this installed version, run: type -a apetrader"
    "A previous curl installation in ~/.local/bin may precede Homebrew on PATH."
    "Run Homebrew's copy directly with: $(brew --prefix)/bin/apetrader"
    "Keep one installation method to avoid conflicting updates."
  end

  # No zap stanza required
end
