# This file was generated by GoReleaser. DO NOT EDIT.
cask "apeyolo" do
  version "0.0.4"

  on_macos do
    on_intel do
      sha256 "15ab424da60dda39817316698251274bce49c23468da841d68aa27e6017eb616"
      url "https://github.com/bearhedge/APEY0L0_v0.0.2/releases/download/v#{version}/apeyolo-mac-x86_64.tar.gz"
    end
    on_arm do
      sha256 "3ca6c8f045df21d5c005df1905f35a578dd8fbd79b03f62fd29399a2f8b40a29"
      url "https://github.com/bearhedge/APEY0L0_v0.0.2/releases/download/v#{version}/apeyolo-mac-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5413bd70ad73861c522a87fcf040f8308e4d700a6a6ff1cbcdb11d7d0abc02b1"
      url "https://github.com/bearhedge/APEY0L0_v0.0.2/releases/download/v#{version}/apeyolo-linux-x86_64.tar.gz"
    end
    on_arm do
      sha256 "6181e049b9eaef377b55bde9ea84f8f92b62c77ec338a4736524bf7a591ff6db"
      url "https://github.com/bearhedge/APEY0L0_v0.0.2/releases/download/v#{version}/apeyolo-linux-arm64.tar.gz"
    end
  end

  name "apeyolo"
  desc "Terminal-based AI trading assistant for 0DTE SPY/SPX options."
  homepage "https://github.com/bearhedge/APEY0L0_v0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "apeyolo"

  # No zap stanza required

end
