# This file was generated by GoReleaser. DO NOT EDIT.
cask "apeyolo" do
  version "0.0.3"

  on_macos do
    on_intel do
      sha256 "01ddcdb825001dc8fdc1de11318d9382e64ff0ec4e67e1fb568aa6843a6263e1"
      url "https://github.com/bearhedge/APEY0L0_v0.0.2/releases/download/v#{version}/apeyolo-mac-x86_64.tar.gz"
    end
    on_arm do
      sha256 "9b5afbe2b7f5ce058c6470956b0eea5efaf3b46bf308b8037cc6c016ba2d6912"
      url "https://github.com/bearhedge/APEY0L0_v0.0.2/releases/download/v#{version}/apeyolo-mac-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "555e4292ba5e90074abea27754c5db6bcdadef905ac5af8a0043ba2d2b072d8b"
      url "https://github.com/bearhedge/APEY0L0_v0.0.2/releases/download/v#{version}/apeyolo-linux-x86_64.tar.gz"
    end
    on_arm do
      sha256 "9ed3f2e677832d04a04ca543881a0394b3047ba35e6638218bdc333ce1d25726"
      url "https://github.com/bearhedge/APEY0L0_v0.0.2/releases/download/v#{version}/apeyolo-linux-arm64.tar.gz"
    end
  end

  name "apeyolo"
  desc "Terminal-based AI trading assistant for 0DTE SPY/SPX options."
  homepage "https://github.com/bearhedge/APEY0L0_v0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "apeyolo"

  # No zap stanza required

end
